name: Entorno de Integración Continua

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Asegura la instalación de una versión reciente de pnpm

      - name: 3. Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 4. Instalar dependencias
        run: pnpm install

      - name: 5. Ejecutar Prueba Automatizada
        run: pnpm test

      - name: 6. Preparar sitio para GitHub Pages
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 1. Desplegar sitio en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4